import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./layouts";
import { Providers } from "@/components/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className={inter.variable} suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers>
          <main className="w-full">
            <Header />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
